### ISSUE TITLE
Support for multiple assemblies

### ISSUE THREAD

**Issue by eagerestwolf** [ap0llo/mddocs#112]
First of all, great tool. This paired with Docsify or MkDocs blows DocFX out of the water. One thing that [Vsxmd](https://github.com/lijunle/Vsxmd) and DocFX do support that I think is sorely missing here, is the ability to output the docs for multiple assemblies to the same path. For example, say you have a library that's broken into 3 or 4 parts because the others add to the original. With the current setup of this tool, it's not possible to output those docs to the same directory since the tool deletes anything in the folder upon initiation. Further complicating matters since this tool creates a folder structure that mimics the namespaces (not a bad thing), you would have to move folders around to create the desired layout. Not hard on my computer, but really difficult to account for during CI. An idea on what I'm talking about, let's say I have the folder structure shown below

- docs/
  - api/
  - *all the docs*
  - README.md
- src/
  - LibA
    - *other files I don't feel like listing*
    - LibA.csproj
  - LibB
    - *again, other files I don't feel like listing*
    - LibB.csproj

Obviously, we'll assume LibA and LibB share a namespace, say `RootNamespace`, so we have `RootNamespace.LibA` and `RootNamespace.LibB`. Then I run `dotnet mddocs apireference -a src/LibA/bin/Debug/net5.0/LibA.dll -o docs/api/` everything works as expected; but if I then do `dotnet mddocs apireference -a src/LibB/bin/Debug/net5.0/LibB.dll -o docs/api/` everything in the `api/` folder gets deleted first. That's smart for incremental building, so old APIs don't get left in the documentation, but it has the unintended side effect that multi-project libraries can't put their documentation together.

I do realize this is a very niche problem, but it's becoming a lot more common in the dotnet world to have a larger project broken into multiple smaller subprojects.

**Comment by ap0llo** [comment]
Thank you for your feedback, I'm glad to hear you find this little tool useful.

I can definitely see the use case for multi-assembly support and would like to add it, I've just never come around to implementing it.

**Comment by eagerestwolf** [comment]
You're certainly welcome. This is a nice change that there is superior and honestly more user friendly alternative to [DocFX](https://github.com/dotnet/docfx). I mean DocFX was great back in the day, but the dotnet core support is spotty at best and V3 has been in development hell for years. The only other competing solution I was aware of was [Wyam](https://wyam.io/), but support ended a while ago. [Vsxmd](https://github.com/lijunle/Vsxmd) is great a great concept, but its output is fugly.

I did have a quick sneak peek at your code, and it didn't seem like it would be too difficult on the backend to implement, just a quick template adjustment. I would imagine the hard part is the cli implementation.

**Comment by ap0llo** [comment]
> I did have a quick sneak peek at your code, and it didn't seem like it would be too difficult on the backend to implement, just a quick template adjustment. I would imagine the hard part is the cli implementation.

I'm not sure what you mean by cli implementation, but the must important thing that would need to be changed is the model. 
That is currently centered around a sinlge assembly (the `AssemblyDocumentation` model class). It would need to be expanded to allow for multiple assemblies and the identity types (foremost `TypeId`) would need to be enabled to reference types across assembly boundaries. Also, I'm not sure if it would need to handle conflicts when a type with the same name is defined in both assemblies.

(Wyam was developed into [Statiq](https://statiq.dev/) btw)

**Comment by eagerestwolf** [comment]
@ap0llo hey, sorry it's been a minute, things have been kinda crazy at my normal job. What I was referring to was the CLI support for determining whether one assembly or multiple had been passed, but I forgot that you are using a model based approach. Also, I was aware of Statiq, but I don't really count it as it's so far detached from the other solutions, you can't really just publish a Statiq site straight to Github Pages like you can with Wyam, DocFX, and Docsify.

**Comment by ap0llo** [comment]
I had some time this weekend and started working on this (#123). 

I'm giving no guarantees when I will finish though 😉

**Comment by ap0llo** [comment]
This should now work in version 0.5.64-pre (available in the MyGet feed).
I'd appreciate feedback if this works as expected.

**Comment by SonofNun15** [comment]
Any plans to deploy this prerelease as a normal release on NuGet at some point? Interested in the simplicity of this solution for generating documentation that works well with source control and can be built as part of an automated process from xdoc comments, but would be nice to not have to pull a prerelease version from MyGet and we'll definitely need the ability to pull from multiple assemblies.
